// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	image: {
		repository: "localhost:5000/mario-friends/mario-friends"
		digest:     ""
		tag:        "1.0.0-dev"
		pullPolicy: "Always"
	}
	test: image: {
		repository: "localhost:5000/mario-friends/mario-friends"
		digest:     ""
		tag:        "1.0.0-dev"
	}
	service: port: 8080
}
